/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lumidigm_vcomdroid_VCOM */

#ifndef _Included_lumidigm_vcomdroid_VCOM
#define _Included_lumidigm_vcomdroid_VCOM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_Open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1Open
  (JNIEnv *, jobject, jint);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1Close
  (JNIEnv *, jobject);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_Ping
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1Ping
  (JNIEnv *, jobject);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_Capture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1Capture
  (JNIEnv *, jobject);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_GetSpoofScore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1GetSpoofScore
  (JNIEnv *, jobject);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_GetMatchScore
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1GetMatchScore
  (JNIEnv *, jobject);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_GetCompositeImageSizeX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1GetCompositeImageSizeX
  (JNIEnv *, jobject);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_GetCompositeImageSizeY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1GetCompositeImageSizeY
  (JNIEnv *, jobject);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_GetCompositeImage
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1GetCompositeImage
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_GetTemplateSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1GetTemplateSize
  (JNIEnv *, jobject);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_GetTemplate
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1GetTemplate
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     lumidigm_vcomdroid_VCOM
 * Method:    JNI_Match
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_lumidigm_vcomdroid_VCOM_JNI_1Match
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
