/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_otot_barcode_BarcodeWdc */

#ifndef _Included_com_otot_barcode_BarcodeWdc
#define _Included_com_otot_barcode_BarcodeWdc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_otot_barcode_BarcodeWdc
 * Method:    BarcodePower
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_otot_barcode_BarcodeWdc_BarcodePower
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
